### PR TITLE
Pendant integration

### PR DESCRIPTION
**Pull request by bit-pirate**
Motion retargeting from pendant (e.g. Robotis Bioloid) to Robosem

This PR contains #26. Need to merge that one first or rebase.

### CODE REVIEW

**Comment by bit-pirate** [comment]
<del>All good here.</del> wrong issue ...

**Comment by po1** [comment]
What is the state of this PR?
Should anybody review it?

**Comment by bit-pirate** [comment]
I'll tackle this again in a few weeks time and will clear out this PR (merge or close).

**Comment by bit-pirate** [comment]
This PR is fine. Merging.

**Pull request merged**
