### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by bit-pirate**
- improves scaling for hand adaption method
- adds support of collision checking
- implements self-collision checking using MoveIt
- implements collision checking for Korus

### CODE REVIEW

**Comment by bit-pirate** [comment]
@stonier please check.

**Comment by po1** [comment]
@bit-pirate could you please remove the eclipse files .project and .cproject?

**Comment by stonier** [comment]
Looks fine marcus.

:neckbeard:

**Comment by bit-pirate** [comment]
@po1 just start using eclipse! :-P

**Comment by bit-pirate** [comment]
I re-based the PR to squash the commits.

**Pull request merged**
